version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 20
        - nvm use 20
        - node -v
        - npm install
    build:
      commands:
        - npx nx build angular-task  # ✅ Build the Angular app instead of serving it
  artifacts:
    baseDirectory: dist/apps/angular-task  # ✅ Ensure it points to the correct build output
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*