version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 20
        - nvm use 20
        - node -v
        - npm install
    build:
      commands:
        - npx nx build angular-task
  artifacts:
    baseDirectory: dist/apps/angular-task
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
  deploy:
    timeout: 30