version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 20
        - nvm use 20
        - node -v
        - npm install
    build:
      commands:
        - npm run build
    serve:
      commands:
        - npx nx serve angular-task
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*