version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 20
        - nvm use 20
        - node -v
        - npm ci
    build:
      commands:
        - npx nx run angular-task:build
  artifacts:
    baseDirectory: dist/apps/angular-task
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*